version: "3.7"
services:
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    networks:
      - api-network
    ports:
      - 27017:27017   
  api_service:
    build: .
    restart: always
    networks:
      - api-network
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
networks:
  api-network:         